export const entries = [
  { name: 'Jero Mae C. Piang', addres: 'Novice Women' },
  { name: 'Ruchel Bolano', addres: 'Novice Women' },
  { name: 'Del Olavides', addres: 'Novice Women' },
  { name: 'Melanie Daluz', addres: 'Novice Women' },
  { name: 'Carol Zuzzane Saga', addres: 'Novice Women' },
  { name: 'Mae Marie C. Tagaan', addres: 'Novice Women' },
  { name: 'Joliza Ganase', addres: 'Novice Women' },
  { name: 'Arrah Tubac', addres: 'Novice Women' },
  { name: 'Marcus Egbus', addres: 'Novice Women' },
  { name: 'Angel Barquin', addres: 'Novice Women' },
  { name: 'Pinky', addres: 'Novice Women' },
  { name: 'Reyn Cabug', addres: 'Novice Women' },
  { name: 'Karen Francisco', addres: 'Novice Women' },
  { name: 'Milky Chiong', addres: 'Novice Women' },
  { name: 'Jaexan Jame Mutia', addres: 'Novice Women' },
  { name: 'Roxanne Mutia', addres: 'Novice Women' },
  { name: 'Gemma Lumacad', addres: 'Novice Women' },
  { name: 'Devy Agonoy', addres: 'Novice Women' },
  { name: 'Honey Blaze Paglinawan', addres: 'Novice Women' },
  { name: 'Jett Tuano', addres: 'Novice Women' },
  { name: 'Elah Mae Maglasang', addres: 'Novice Women' },
  { name: 'Christyle Mae Villegas', addres: 'Novice Women' },
  { name: 'Kimberlyn Buntog', addres: 'Novice Women' },
  { name: 'Maria Erica Ligason', addres: 'Novice Women' },
  { name: 'Cherry Banque', addres: 'Novice Women' },
  { name: 'Lesli Abais', addres: 'Novice Women' },
  { name: 'Genevie Sotto', addres: 'Novice Women' },
  { name: 'Cassandra Dominguez', addres: 'Novice Women' },
  { name: 'Edcel Grace Cobrilla', addres: 'Novice Women' },
  { name: 'Quevy Semillano', addres: 'Novice Women' },
  { name: 'Jerrylyn Painagan', addres: 'Novice Women' },
  { name: 'Jesabel M. Dolorican', addres: 'Novice Women' },
  { name: 'Gladys laranjo', addres: 'Novice Women' },
  { name: 'Princess Ida Aruelo', addres: 'Novice Women' },
  { name: 'Cyril Bernido', addres: 'Novice Women' },
  { name: 'Anjeanette Guigue', addres: 'Novice Women' },
  { name: 'Sean Rafael T. Cang', addres: 'Novice Women' },
  { name: 'Mary Grace Bernido', addres: 'Novice Women' },
  { name: 'Griffith Egbus', addres: 'Novice Women' },
  { name: 'Richen Dela Cruz', addres: 'Novice Women' },
  { name: 'Sigrid Ortizo', addres: 'Novice Women' },
  { name: 'Lady Shamma Bello', addres: 'Novice Women' },
  { name: 'Indee Ricaforte', addres: 'Novice Women' },
  { name: 'Sherrie Dea Martir', addres: 'Novice Women' },
  { name: 'Julieta Suson', addres: 'Novice Women' },
  { name: 'Reiji Jace Mutia', addres: 'Novice Women' },
  { name: 'Giselle Medina', addres: 'Novice Women' },
  { name: 'Melchiefair Christine Nisnisan', addres: 'Novice Women' },
  { name: 'Mae Vince Calderon', addres: 'Novice Women' },
  { name: 'Remedios Fernandez', addres: 'Novice Women' },
  { name: 'Sky Lacida', addres: 'Novice Women' },
  { name: 'Roela Jezelle  Enomar', addres: 'Novice Women' },
  { name: 'Christine Villegas Ethyle', addres: 'Novice Women' },
  { name: 'Rose Carmelie Collantes', addres: 'Novice Women' },
  { name: 'Irene Penales', addres: 'Novice Women' },
  { name: 'Harlene Tan', addres: 'Novice Women' },
  { name: 'Meryl Calamba', addres: 'Novice Women' },
  { name: 'Cheeny Pasok', addres: 'Novice Women' },
  { name: 'Maria Sofia Abarco', addres: 'Novice Women' },
  { name: 'Aura Kaye Taladua', addres: 'Novice Women' },
  { name: 'Angel Fernandez', addres: 'Novice Women' },
  { name: 'Carmi Candano', addres: 'Novice Women' },
  { name: 'IVAN VHER C. TUBAL', address: 'Novice Men' },
  { name: 'Anthony Uy', address: 'Novice Men' },
  { name: 'FRITZ V. MABIDA', address: 'Novice Men' },
  { name: 'Liam Densing', address: 'Novice Men' },
  { name: 'Jairus Paica', address: 'Novice Men' },
  { name: 'KC Sumalpong', address: 'Novice Men' },
  { name: 'Karl Kagas', address: 'Novice Men' },
  { name: 'Fernando Rey Cotales', address: 'Novice Men' },
  { name: 'Joshua Bulawin', address: 'Novice Men' },
  { name: 'Ear Aguirre', address: 'Novice Men' },
  { name: 'JAY MARNEL BALO', address: 'Novice Men' },
  { name: 'Jonel Alcasid', address: 'Novice Men' },
  { name: 'Abiel Kane Pasamanero', address: 'Novice Men' },
  { name: 'Glendair Benida', address: 'Novice Men' },
  { name: 'Patrick James Obut', address: 'Novice Men' },
  { name: 'Danny Te', address: 'Novice Men' },
  { name: 'Alberto C. Panto', address: 'Novice Men' },
  { name: 'Maxwell Fernandez', address: 'Novice Men' },
  { name: 'Christian Dave Tan', address: 'Novice Men' },
  { name: 'James Rafael Siao', address: 'Novice Men' },
  { name: 'Jhon Jeric B. Lobitaña', address: 'Novice Men' },
  { name: 'Dybhon Reyes', address: 'Novice Men' },
  { name: 'Neil Marvin Lucero', address: 'Novice Men' },
  { name: 'Darbhen Sotto', address: 'Novice Men' },
  { name: 'Alfredo Tagaro', address: 'Novice Men' },
  { name: 'Christian Vente', address: 'Novice Men' },
  { name: 'Kenneth Roces', address: 'Novice Men' },
  { name: 'Ralston Regalado', address: 'Novice Men' },
  { name: 'Matthew Philip B. Avelino', address: 'Novice Men' },
  { name: 'Ronald Bryan B. Sabio', address: 'Novice Men' },
  { name: 'Nappie Limpang', address: 'Novice Men' },
  { name: 'Robecon Ralph Tan', address: 'Novice Men' },
  { name: 'Amiel Bryan Manreal   ', address: 'Novice Men' },
  { name: 'Charles Galindo', address: 'Novice Men' },
  { name: 'Benzel Obut', address: 'Novice Men' },
  { name: 'Marco Francisco', address: 'Novice Men' },
  { name: 'Reysim Albetria', address: 'Novice Men' },
  { name: 'Robie Murallon', address: 'Novice Men' },
  { name: 'Francis Jay Anthony Mantuhac', address: 'Novice Men' },
  { name: 'Gleen Salvador', address: 'Novice Men' },
  { name: 'EDWARD S. AGUIRRE', address: 'Novice Men' },
  { name: 'Joseph Doria', address: 'Novice Men' },
  { name: 'Sam Uziel Cabiles', address: 'Novice Men' },
  { name: 'Terrence Molina', address: 'Novice Men' },
  { name: 'Sherwin Cagas', address: 'Novice Men' },
  { name: 'Carewot Boquia', address: 'Novice Men' },
  { name: 'Alben Jake Taclob', address: 'Novice Men' },
  { name: 'Tristan Jacob Jimenez', address: 'Novice Men' },
  { name: 'OZZY ROLEX SALONGA', address: 'Novice Men' },
  { name: 'Randil Ostia', address: 'Novice Men' },
  { name: 'Grant Anthony Campeciño', address: 'Novice Men' },
  { name: 'Christian Kent Roferos', address: 'Novice Men' },
  { name: 'Jan Jasper Obut', address: 'Novice Men' },
  { name: 'Joseph Tumarao Jr.', address: 'Novice Men' },
  { name: 'Abdul Jaffar D. Amer', address: 'Novice Men' },
  { name: 'Gideon Padilla', address: 'Novice Men' },
  { name: 'Charles Irvin Tan', address: 'Novice Men' },
  { name: 'Kane Justine Lee', address: 'Novice Men' },
  { name: 'Kirk Louie Edma', address: 'Novice Men' },
  { name: 'Robert Castro', address: 'Novice Men' },
  { name: 'Renos Amor', address: 'Novice Men' },
  { name: 'RJ Tuano', address: 'Novice Men' },
  { name: 'Jay R Migrinio', address: 'Novice Men' },
  { name: 'Melrey Ferpas', address: 'Novice Men' },
  { name: 'Nordsund Salvanera', address: 'Novice Men' },
  { name: 'Carlo Mananggit', address: 'Novice Men' },
  { name: 'Donato P. Caponong V', address: 'Novice Men' },
  { name: 'Jayward R. Guerra', address: 'Novice Men' },
  { name: 'Dave Alegrado', address: 'Novice Men' },
  { name: 'June Francis Roasol', address: 'Novice Men' },
  { name: 'Arjohn Macarate   ', address: 'Novice Men' },
  { name: 'Archer Mabanag', address: 'Novice Men' },
  { name: 'John Mogn Rosales', address: 'Novice Men' },
  { name: 'Mario Francisco', address: 'Novice Men' },
  { name: 'Laurence Rosal', address: 'Novice Men' },
  { name: 'Dhave Murallon', address: 'Novice Men' },
  { name: 'Shanty Villarin Sison', address: 'Beginner Men' },
  { name: 'Jaime Acaba', address: 'Beginner Men' },
  { name: 'Fulvio Kim Harina', address: 'Beginner Men' },
  { name: 'Karlo Rean Basalo', address: 'Beginner Men' },
  { name: 'Yehoshua Cruz', address: 'Beginner Men' },
  { name: 'Jonkelly Bala', address: 'Beginner Men' },
  { name: 'Galbraith Sean B. Andoy', address: 'Beginner Men' },
  { name: 'Radel Paglinawan', address: 'Beginner Men' },
  { name: 'Ronald Bryan B. Sabio', address: 'Beginner Men' },
  { name: 'Jomie Estomago', address: 'Beginner Men' },
  { name: 'Bon reyes', address: 'Beginner Men' },
  { name: 'Mark Jay Letran', address: 'Beginner Men' },
  { name: 'Marga Gulebban', address: 'Beginner Men' },
  { name: 'Don Almonte', address: 'Beginner Men' },
  { name: 'Estelito Gerodias', address: 'Beginner Men' },
  { name: 'Dalfer Saavedra', address: 'Beginner Men' },
  { name: 'Cris Academia', address: 'Beginner Men' },
  { name: 'Marven Cang', address: 'Beginner Men' },
  { name: 'Lordson Montero', address: 'Beginner Men' },
  { name: 'Chris James Villegas', address: 'Beginner Men' },
  { name: 'Keene Barquin', address: 'Beginner Men' },
  { name: 'Cid T. Valle', address: 'Beginner Men' },
  { name: 'Cher Leo', address: 'Beginner Men' },
  { name: 'Kier Cagas', address: 'Beginner Men' },
  { name: 'Onin Handugan', address: 'Beginner Men' },
  { name: 'Thomas Jacob Saladaga', address: 'Beginner Men' },
  { name: 'Jun Gil Aninon', address: 'Beginner Men' },
  { name: 'Emiliano Pielago', address: 'Beginner Men' },
  { name: 'Rey Ann Malalis', address: 'Beginner Men' },
  { name: 'Roland Cagas', address: 'Beginner Men' },
  { name: 'Christian Rey Galior', address: 'Beginner Men' },
  { name: 'Matthew Philip B. Avelino', address: 'Beginner Men' },
  { name: 'Leo Gerocho', address: 'Beginner Men' },
  { name: 'Rudjohn Rizon', address: 'Beginner Men' },
  { name: 'Johnson Dahab', address: 'Beginner Men' },
  { name: 'Ryan Jay Cañedo', address: 'Beginner Men' },
  { name: 'JP Gultiano', address: 'Beginner Men' },
  { name: 'Ryan Niño Bodiongan', address: 'Beginner Men' },
  { name: 'Kent Lagar', address: 'Beginner Men' },
  { name: 'YanYan Ocampos', address: 'Beginner Men' },
  { name: 'John Benedict C. Dolorican', address: 'Beginner Men' },
  { name: 'Bjo Alima', address: 'Beginner Men' },
  { name: 'Garry aguirre', address: 'Beginner Men' },
  { name: 'John Michael Ceniza', address: 'Beginner Men' },
  { name: 'Icy Bercris', address: 'Beginner Men' },
  { name: 'EJ Ramirez', address: 'Beginner Men' },
  { name: 'Jumarie Paden', address: 'Beginner Men' },
  { name: 'Delon Caylan', address: 'Beginner Men' },
  { name: 'Ranjie Saavedra', address: 'Beginner Men' },
  { name: 'William Adorable', address: 'Beginner Men' },
  { name: 'George Omongos', address: 'Beginner Men' },
  { name: 'Bryan James Villegas', address: 'Beginner Men' },
  { name: 'Lemuel Operario', address: 'Beginner Men' },
  { name: 'Ernesto Torres', address: 'Beginner Men' },
  { name: 'Megoy Ogue', address: 'Beginner Men' },
  { name: 'Chan2x', address: 'Beginner Men' },
  { name: 'Jericho Villez', address: 'Beginner Men' },
  { name: 'Jesus Sanciangco', address: 'Beginner Men' },
  { name: 'Kenver John Bicoy', address: 'Beginner Men' },
  { name: 'Ryan Javier', address: 'Beginner Men' },
  { name: 'Joselito Rosalijos', address: 'Beginner Men' },
  { name: 'Cipriano Baron', address: 'Beginner Men' },
  { name: 'Jhuvanne Abendano', address: 'Beginner Men' },
  { name: 'Donato P. Caponong V', address: 'Beginner Men' },
  { name: 'Conchessa Christine Tan', address: 'Beginner Women' },
  { name: 'Cling Bitas', address: 'Beginner Women' },
  { name: 'Jackelyn Marie Y. Regalado', address: 'Beginner Women' },
  { name: 'Maria Anafe Florame Vioen S. Fernandez', address: 'Beginner Women' },
  { name: 'Shayne Nailil', address: 'Beginner Women' },
  { name: 'Judy Paler', address: 'Beginner Women' },
  { name: 'Christian Joy Dela Cerna', address: 'Beginner Women' },
  { name: 'Sofia Maglasang', address: 'Beginner Women' },
  { name: 'Sheena Faye O. Bacaling', address: 'Beginner Women' },
  { name: 'Jean Salaveria Cenas', address: 'Beginner Women' },
  { name: 'Jude Pambuena', address: 'Beginner Women' },
  { name: 'Analiza Cabctulan', address: 'Beginner Women' },
  { name: 'Murbeth Rhyme Oliveros', address: 'Beginner Women' },
  { name: 'Maychelle Dagang', address: 'Beginner Women' },
  { name: 'Libby Gen Cuizon', address: 'Beginner Women' },
  { name: 'Guelah Enerio', address: 'Beginner Women' },
  { name: 'Myra Mae Tapere', address: 'Beginner Women' },
  { name: 'Chery Mae Dalman', address: 'Beginner Women' },
  { name: 'Beah Torres', address: 'Beginner Women' },
  { name: 'Jane Kathleen Caritos', address: 'Beginner Women' },
  { name: 'Alice Abregana', address: 'Beginner Women' },
  { name: 'April Mae Atillo', address: 'Beginner Women' },
  { name: 'Pinky Cagas', address: 'Beginner Women' },
  { name: 'Marjorie Alarva', address: 'Beginner Women' },
  { name: 'Emma Quilo', address: 'Beginner Women' },
  { name: 'Charlyn G. Medequiso', address: 'Beginner Women' },
  { name: 'Mercy Uy', address: 'Beginner Women' },
  { name: 'Shandy Francisco', address: 'Beginner Women' },
  { name: 'Kath Manada', address: 'Beginner Women' },
  { name: 'Stacy Pabatao', address: 'Beginner Women' },
  { name: 'Sherrie Dea Martir', address: 'Beginner Women' },
  { name: 'Quineybel N. Mag-usara', address: 'Beginner Women' },
  { name: 'Cherie Mae Ferrer Lerin', address: 'Beginner Women' },
  { name: 'Joyce Yap', address: 'Beginner Women' },
  { name: 'Honey Paglinawan', address: 'Beginner Women' },
  { name: 'Meliera Joy Villejo', address: 'Beginner Women' },
  { name: 'Josephine Vicente', address: 'Beginner Women' },
  { name: 'Roela Jezelle', address: 'Beginner Women' },
  { name: 'Generose Malon', address: 'Beginner Women' },
  { name: 'Mayvilyn Igot', address: 'Beginner Women' },
  { name: 'Joyce Pabatao', address: 'Beginner Women' },
  { name: 'Ma. Allynn Malaay', address: 'Beginner Women' },
  { name: 'Jane Marie Legaspi', address: 'Beginner Women' },
  { name: 'Aizzle Salavaria', address: 'Beginner Women' },
  { name: 'Saikie Baldoza', address: 'Beginner Women' },
  { name: 'Reyn Cabug', address: 'Beginner Women' },
  { name: 'ZENMAR CLAM', address: 'Beginner Mixed' },
  { name: 'Quineybel N. Mag-usara', address: 'Beginner Mixed' },
  { name: 'Jonkelly Bala', address: 'Beginner Mixed' },
  { name: 'John Calvin C Centino', address: 'Beginner Mixed' },
  { name: 'Rey Ann L.Malalis', address: 'Beginner Mixed' },
  { name: 'Princess Mae Lusing', address: 'Beginner Mixed' },
  { name: 'Kenneth Roses', address: 'Beginner Mixed' },
  { name: 'Cling Bitas', address: 'Beginner Mixed' },
  { name: 'Alive Eve Abregana', address: 'Beginner Mixed' },
  { name: 'Lyndon Olavides', address: 'Beginner Mixed' },
  { name: 'Chester Jabel Lluch', address: 'Beginner Mixed' },
  { name: 'Emma Quilo', address: 'Beginner Mixed' },
  { name: 'Jayward R. Guerra', address: 'Beginner Mixed' },
  { name: 'Katriuna Manada', address: 'Beginner Mixed' },
  { name: 'Marco Francisco', address: 'Beginner Mixed' },
  { name: 'Kier Cagas', address: 'Beginner Mixed' },
  { name: 'Christine Tan', address: 'Beginner Mixed' },
  { name: 'Marlou Abdul', address: 'Beginner Mixed' },
  { name: 'JAY MARNEL BALO', address: 'Beginner Mixed' },
  { name: 'Abby Rondina', address: 'Beginner Mixed' },
  { name: 'Vioen Fernandez', address: 'Beginner Mixed' },
  { name: 'Shan June Rosalijos', address: 'Beginner Mixed' },
  { name: 'Shammah Bello Jan', address: 'Beginner Mixed' },
  { name: 'Jomie Estomago', address: 'Beginner Mixed' },
  { name: 'Sheena Faye O. Bacaling', address: 'Beginner Mixed' },
  { name: 'Mae Vince Calderon', address: 'Beginner Mixed' },
  { name: 'Tara Rebekka Quilang', address: 'Beginner Mixed' },
  { name: 'Keith Mendoza', address: 'Beginner Mixed' },
  { name: 'Domenique Cagaanan', address: 'Beginner Mixed' },
  { name: 'Eleuber Cabillo', address: 'Beginner Mixed' },
  { name: 'Chicoy Chua', address: 'Beginner Mixed' },
  { name: 'Sigrid Ortizo', address: 'Beginner Mixed' },
  { name: 'JAY-ANN ONGOS', address: 'Beginner Mixed' },
  { name: 'Leo R. Gorecho', address: 'Beginner Mixed' },
  { name: 'Maria Sophia Buot Abarco', address: 'Beginner Mixed' },
  { name: 'Rubelyn P Malagamba', address: 'Beginner Mixed' },
  { name: 'Charlene C. Malalis', address: 'Beginner Mixed' },
  { name: 'Jefferson Dy Lusing', address: 'Beginner Mixed' },
  { name: 'Aries Vena', address: 'Beginner Mixed' },
  { name: 'Jeffrey Dano', address: 'Beginner Mixed' },
  { name: 'Mark Jhon P Ogue', address: 'Beginner Mixed' },
  { name: 'Che Olavides', address: 'Beginner Mixed' },
  { name: 'Sofia maglasang', address: 'Beginner Mixed' },
  { name: 'John William Adorable', address: 'Beginner Mixed' },
  { name: 'Jeromae C. Piang', address: 'Beginner Mixed' },
  { name: 'Radel Paglinawan', address: 'Beginner Mixed' },
  { name: 'Karen Francisco', address: 'Beginner Mixed' },
  { name: 'Pinky Cagas', address: 'Beginner Mixed' },
  { name: 'John Mark Galvez', address: 'Beginner Mixed' },
  { name: 'Wendy Abdul', address: 'Beginner Mixed' },
  { name: 'Deomicah Solano-Balo', address: 'Beginner Mixed' },
  { name: 'Danielle Cabrisos', address: 'Beginner Mixed' },
  { name: 'Michael Fernandez', address: 'Beginner Mixed' },
  { name: 'Aileen Rosalijos', address: 'Beginner Mixed' },
  { name: 'Mikko Dulcero', address: 'Beginner Mixed' },
  { name: 'Stacy Golda Pabatao', address: 'Beginner Mixed' },
  { name: 'Rudjohn P. Rizon', address: 'Beginner Mixed' },
  { name: 'Nappie Limpang', address: 'Beginner Mixed' },
  { name: 'Jek Adorable', address: 'Beginner Mixed' },
  { name: 'Julie Marie Laurel', address: 'Beginner Mixed' },
  { name: 'Donabel Jumalon', address: 'Beginner Mixed' },
  { name: 'Remwelette Marie Jaim', address: 'Beginner Mixed' },
  { name: 'Jessica Enerio', address: 'Beginner Mixed' },
  { name: 'SanSan Balais', address: 'Beginner Mixed' },
  { name: 'Yong Dela Cerna', address: 'Intermediate Men' },
  { name: 'Rjun D. Abing', address: 'Intermediate Men' },
  { name: 'LJ Odbina', address: 'Intermediate Men' },
  { name: 'Paul Angelo Saladaga', address: 'Intermediate Men' },
  { name: 'William Vincent B Tan', address: 'Intermediate Men' },
  { name: 'Chael Edrol Fernandez', address: 'Intermediate Men' },
  { name: 'Archer Lunayan', address: 'Intermediate Men' },
  { name: 'Frank Calamba', address: 'Intermediate Men' },
  { name: 'Geremias cajocon', address: 'Intermediate Men' },
  { name: 'Jhuzeel Jatico', address: 'Intermediate Men' },
  { name: 'Ranger Ricaforte', address: 'Intermediate Men' },
  { name: 'Julfred James Yting', address: 'Intermediate Men' },
  { name: 'Daryl Legaspi', address: 'Intermediate Men' },
  { name: 'Jucky Brian Quabo  ', address: 'Intermediate Men' },
  { name: 'Roniel Cabresus ', address: 'Intermediate Men' },
  { name: 'Am Am Ibrahim', address: 'Intermediate Men' },
  { name: 'Sahab', address: 'Intermediate Men' },
  { name: 'Ian Villanueva', address: 'Intermediate Men' },
  { name: 'Danilo Yting', address: 'Intermediate Men' },
  { name: 'Neil Taladua', address: 'Intermediate Men' },
  { name: 'Le Jay J. Villanueva  ', address: 'Intermediate Men' },
  { name: 'Alexis Cimacio', address: 'Intermediate Men' },
  { name: 'Ariel Vargas', address: 'Intermediate Men' },
  { name: 'James Chiong', address: 'Intermediate Men' },
  { name: 'Gagriel M. Tiongco', address: 'Intermediate Men' },
  { name: 'Charles Paculba', address: 'Intermediate Men' },
  { name: 'San2x Cuasito', address: 'Intermediate Men' },
  { name: 'Gabriel Catane', address: 'Intermediate Men' },
  { name: 'Jhon Joseph Bello', address: 'Intermediate Men' },
  { name: 'Joshua Alforo', address: 'Intermediate Men' },
  { name: 'Paolo Montejo', address: 'Intermediate Men' },
  { name: 'Jhon Mark B. Pernito', address: 'Intermediate Men' },
  { name: 'Joshua Catipay', address: 'Intermediate Men' },
  { name: 'Thong Bual', address: 'Intermediate Men' },
  { name: 'John Rainier Anor', address: 'Intermediate Men' },
  { name: 'Miggy Gatab', address: 'Intermediate Men' },
  { name: 'Joezer Malolot  ', address: 'Intermediate Men' },
  { name: 'Christian Ligan ', address: 'Intermediate Men' },
  { name: 'Aljamier Usman', address: 'Intermediate Men' },
  { name: 'Edward', address: 'Intermediate Men' },
  { name: 'Nico Lanzado', address: 'Intermediate Men' },
  { name: 'Ralph Chan', address: 'Intermediate Men' },
  { name: 'Geoffrey Tormis', address: 'Intermediate Men' },
  { name: 'Bryle John Jatico', address: 'Intermediate Men' },
  { name: 'Vincent Raniego', address: 'Intermediate Men' },
  { name: 'Col. Nelvin', address: 'Intermediate Men' },
  { name: 'Evangeline Estrosas', address: 'Intermediate Women' },
  { name: 'Danna Javate', address: 'Intermediate Women' },
  { name: 'Lot Maglasang', address: 'Intermediate Women' },
  { name: 'Alexa Yu', address: 'Intermediate Women' },
  { name: 'Mikka Bambalan', address: 'Intermediate Women' },
  { name: 'Maria Bacsal', address: 'Intermediate Women' },
  { name: 'Ahbee', address: 'Intermediate Women' },
  { name: 'Andrea Chavez', address: 'Intermediate Women' },
  { name: 'Carmel Padilla', address: 'Intermediate Women' },
  { name: 'Cristy Selatona', address: 'Intermediate Women' },
  { name: 'Crexia Babas', address: 'Intermediate Women' },
  { name: 'Eve Abregana', address: 'Intermediate Women' },
  { name: 'Jessica Alima', address: 'Intermediate Women' },
  { name: 'Delan Sailo', address: 'Intermediate Women' },
  { name: 'Sofia Maglasang', address: 'Intermediate Women' },
  { name: 'Myla Vilaanueva', address: 'Intermediate Women' },
  { name: 'Myushi Plariza', address: 'Intermediate Women' },
  { name: 'Jan Marie  Anghag', address: 'Intermediate Women' },
  { name: 'Danilo Yting', address: 'Intermediate Mixed' },
  { name: 'Christy A Selatona                ', address: 'Intermediate Mixed' },
  { name: 'Evangeline Estrosas        ', address: 'Intermediate Mixed' },
  { name: 'Roniel Cabrisos        ', address: 'Intermediate Mixed' },
  { name: 'Aljamier Usman', address: 'Intermediate Mixed' },
  { name: 'Chrisha May Jubay', address: 'Intermediate Mixed' },
  { name: 'Allyn Rose Lacaya', address: 'Intermediate Mixed' },
  { name: 'Jeff Balatero', address: 'Intermediate Mixed' },
  { name: 'Vincent Raniego', address: 'Intermediate Mixed' },
  { name: 'Kelvin Babas', address: 'Intermediate Mixed' },
  { name: 'Danna Ravate', address: 'Intermediate Mixed' },
  { name: 'James Chiong', address: 'Intermediate Mixed' },
  { name: 'Jango Paredes', address: 'Intermediate Mixed' },
  { name: 'Jay Bello', address: 'Intermediate Mixed' },
  { name: 'Frank Calmba', address: 'Intermediate Mixed' },
  { name: 'Faith Abigail Manlantao', address: 'Intermediate Mixed' },
  { name: 'Lj Odbina', address: 'Intermediate Mixed' },
  { name: 'Joshua Gatab', address: 'Intermediate Mixed' },
  { name: 'Shena Echavez        ', address: 'Intermediate Mixed' },
  { name: 'Crexia Babas', address: 'Intermediate Mixed' },
  { name: 'Raj Egama', address: 'Intermediate Mixed' },
  { name: 'Thong Bual        ', address: 'Intermediate Mixed' },
  { name: 'Myla Villanueva', address: 'Intermediate Mixed' },
  { name: 'Andrea Chavez', address: 'Intermediate Mixed' },
  { name: 'Myushe Plariza', address: 'Intermediate Mixed' },
  { name: 'Ollie Joshua Alforo', address: 'Intermediate Mixed' },
  { name: 'Jessica Alima', address: 'Intermediate Mixed' },
  { name: 'April Cuizon', address: 'Intermediate Mixed' },
  { name: 'Alexandrine Yu', address: 'Intermediate Mixed' },
  { name: 'Anna Marie Mendoza', address: 'Intermediate Mixed' },
  { name: 'Ranger', address: 'Open' },
  { name: 'Jeff Balatero', address: 'Open' },
  { name: 'William Vincent Tan', address: 'Open' },
  { name: 'Am Am Ibrahim', address: 'Open' },
  { name: 'Sahab', address: 'Open' },
  { name: 'Arnold Chiong', address: 'Open' },
  { name: 'Sun Lacida', address: 'Open' },
  { name: 'Jasper Villamor', address: 'Open' },
  { name: 'Vincent Raniego', address: 'Open' },
  { name: 'James Chiong ', address: 'Open' },
  { name: 'Algen Olivar', address: 'Open' },
  { name: 'Kiko Ismael', address: 'Open' },
  { name: 'Danilo Yting', address: 'Open' },
  { name: 'Joshua Gatab', address: 'Open' },
  { name: 'Gabriel Catane', address: 'Open' },
  { name: 'Thong', address: 'Open' },
  { name: 'Errol', address: 'Open' },
  { name: 'Francis Lanzado', address: 'Open' },
  { name: 'Moon Lacida', address: 'Open' },
  { name: 'Raj Egama', address: 'Open' },
  { name: 'Jed Juario', address: 'Open' },
  { name: 'Cj Ligan', address: 'Open' },
  { name: 'Rjun Abing', address: 'Open' },
  { name: 'Claver Viviano', address: 'Open' }
]
